# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- develop

pool:
  vmImage: ubuntu-latest

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

steps:
- script: |
    npm install -g serverless
  displayName: 'Install Serverless'

- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- task: Cache@2
  inputs:
    key: '"yarn" | "$(Agent.OS)" | yarn.lock'
    restoreKeys: |
       yarn | "$(Agent.OS)"
       yarn
    path: $(YARN_CACHE_FOLDER)
  displayName: 'Cache Yarn packages'

- script: yarn --frozen-lockfile
  displayName: 'Install packages'

- bash: sls deploy --stage qas --verbose
  displayName: 'Serverless Deploy QAS'
  env:
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
    DB_CLIENT: $(DB_CLIENT)
    DB_HOST: $(DB_HOST)
    DB_PORT: $(DB_PORT)
    DB_NAME: $(DB_NAME)
    DB_USER: $(DB_USER)
    DB_PASSWORD: $(DB_PASSWORD)
    API_KEY: $(API_KEY)
    JWTSecret: $(JWTSecret)
    RECEITAWS_API_TOKEN: $(RECEITAWS_API_TOKEN)